export const countries = [
    { name: 'Belgium', isoCode: 'BE' },
    { name: 'Bulgaria', isoCode: 'BG' },
    { name: 'Chile', isoCode: 'CL' },
    { name: 'China', isoCode: 'CN' },
    { name: 'Colombia', isoCode: 'CO' },
    { name: 'Egypt', isoCode: 'EG' },
    { name: 'Finland', isoCode: 'FI' },
    { name: 'France', isoCode: 'FR' },
    { name: 'Germany', isoCode: 'DE' },
    { name: 'Hong Kong', isoCode: 'HK' },
    { name: 'India', isoCode: 'IN' },
    { name: 'Ireland', isoCode: 'IE' },
    { name: 'Italy', isoCode: 'IT' },
    { name: 'Japan', isoCode: 'JP' },
    { name: 'Kenya', isoCode: 'KE' },
    { name: 'Macau', isoCode: 'MO' },
    { name: 'Malta', isoCode: 'MT' },
    { name: 'Mexico', isoCode: 'MX' },
    { name: 'New Zealand', isoCode: 'NZ' },
    { name: 'Peru', isoCode: 'PE' },
    { name: 'Spain', isoCode: 'ES' },
    { name: 'Taiwan', isoCode: 'TW' },
    { name: 'Thailand', isoCode: 'TH' },
    { name: 'United Kingdom', isoCode: 'GB' },
    { name: 'United States', isoCode: 'US' },
]
