export const hotelsSemanticTokens: {
    hotelName: string
    semanticTokens: string[]
}[] = [
    {
        hotelName: 'Sai Kaew Beach Resort',
        semanticTokens: [
            'beach',
            'resort',
            'say',
            'kaw',
            'keau',
            'beech',
            'resrt',
            'say kew',
            'sigh cow',
            'kew',
            'resot',
            'saikaew',
            'beachresort',
            'samet',
            'sammet',
            'thailand',
            'beachfront',
            'seaside',
            'coastal',
            'waterfront',
            'pool',
            'swimming',
            'ocean view',
        ],
    },
    {
        hotelName: 'Marine Hotel',
        semanticTokens: [
            'marine',
            'hotel',
            'marin',
            'marinn',
            'mariyne',
            'hotell',
            'mareen',
            'mareene',
            'hotle',
            'marnie',
            'mraine',
            'hoetl',
            'htoel',
            'dublin',
            'sutton',
            'ireland',
            'business',
            'city',
            'urban',
            'harbour',
            'marinehotel',
        ],
    },
    {
        hotelName: 'TRYP Malaga Alameda Hotel',
        semanticTokens: [
            'tryp',
            'malaga',
            'alameda',
            'trip',
            'tripp',
            'mallaga',
            'almeda',
            'treep',
            'malaaga',
            'trypp',
            'malga',
            'almada',
            'melia',
            'spain',
            'andalusia',
            'business',
            'convention',
            'tryphotel',
            'downtown',
        ],
    },
    {
        hotelName: 'NH Iquique Hotel',
        semanticTokens: [
            'nh',
            'iquique',
            'hotel',
            'en aitch',
            'ikique',
            'nh hotels',
            'ikike',
            'enach',
            'coastal',
            'pacific',
            'business',
            'corporate',
            'beach',
            'oceanfront',
            'nhhotel',
            'chile',
        ],
    },

    {
        hotelName: 'Sheraton Grand Hotel & Spa, Edinburgh',
        semanticTokens: [
            'sheraton',
            'grand',
            'hotel',
            'spa',
            'edinburgh',
            'shearton',
            'sheratun',
            'grandd',
            'edinburg',
            'sheritan',
            'edinbura',
            'sharaton',
            'grnad',
            'edinbrugh',
            'marriott',
            'starwood',
            'sheratongrand',
            'luxury',
            'premium',
            'scotland',
            'wellness',
            'massage',
            'pool',
        ],
    },
    {
        hotelName: 'Kew Green Hotel Wanchai Hong Kong',
        semanticTokens: [
            'kew',
            'green',
            'wanchai',
            'hongkong',
            'kue',
            'gren',
            'wanchie',
            'kewgreen',
            'business',
            'corporate',
            'hennessy',
            'central',
            'downtown',
            'harbour',
            'international',
            'kewgreenhotel',
            'asia',
        ],
    },
    {
        hotelName: 'Hotel Dann Carlton Medellin',
        semanticTokens: [
            'dann',
            'carlton',
            'medellin',
            'dan',
            'carleton',
            'carlten',
            'danncarlton',
            'luxury',
            'business',
            'corporate',
            'upscale',
            'premium',
            'colombia',
            'populated',
            'hotelcarlton',
        ],
    },
    {
        hotelName: 'Grand Coloane Resort',
        semanticTokens: [
            'grand',
            'coloane',
            'resort',
            'grand',
            'colon',
            'macau',
            'grnad',
            'resort',
            'resrt',
            'casino',
            'gaming',
            'luxury',
            'beach',
            'premium',
            'waterfront',
            'grandresort',
            'vacation',
        ],
    },
    {
        hotelName: 'SKYCITY Hotel',
        semanticTokens: [
            'skycity',
            'sky',
            'city',
            'hotel',
            'skyecity',
            'skicity',
            'scycity',
            'skcity',
            'skyciti',
            'skyctiy',
            'skycyte',
            'skycityhotel',
            'auckland',
            'casino',
            'gaming',
            'entertainment',
            'convention',
            'business',
        ],
    },
    {
        hotelName: 'Pullman Bordeaux Lac',
        semanticTokens: [
            'pullman',
            'bordeaux',
            'lac',
            'pulman',
            'bordeux',
            'lake',
            'pullmann',
            'bordo',
            'accor',
            'wine',
            'business',
            'meetings',
            'corporate',
            'congress',
            'convention',
            'exhibition',
            'upscale',
            'pullmanhotel',
        ],
    },
    {
        hotelName: 'Hotel Conde Luna',
        semanticTokens: [
            'conde',
            'luna',
            'moon',
            'leon',
            'condy',
            'luna',
            'historic',
            'central',
            'downtown',
            'city',
            'castle',
            'business',
            'medieval',
            'condeluna',
            'hotelconde',
            'spain',
        ],
    },
    {
        hotelName: 'Park Suisse Hotel',
        semanticTokens: [
            'park',
            'suisse',
            'swiss',
            'santa margherita',
            'liguria',
            'parks',
            'swisse',
            'parksuisse',
            'mediterranean',
            'riviera',
            'coastal',
            'seaside',
            'vacation',
            'holiday',
            'boutique',
            'beach',
            'waterfront',
            'italy',
        ],
    },
    {
        hotelName: 'Hotel Agua Escondida',
        semanticTokens: [
            'agua',
            'water',
            'escondida',
            'taxco',
            'aguas',
            'escondido',
            'hidden',
            'colonial',
            'historic',
            'silver',
            'mountain',
            'boutique',
            'traditional',
            'aguahotel',
            'mexico',
        ],
    },
    {
        hotelName: 'Hotel Caribe Cartagena',
        semanticTokens: [
            'caribe',
            'caribbean',
            'cartagena',
            'carib',
            'cartegena',
            'beach',
            'historic',
            'colonial',
            'waterfront',
            'oceanfront',
            'tropical',
            'luxury',
            'resort',
            'caribbeansea',
            'colombia',
        ],
    },
    {
        hotelName: 'Haihua Hotel Hangzhou',
        semanticTokens: [
            'haihua',
            'hangzhou',
            'hai',
            'hua',
            'hangzou',
            'haihau',
            'business',
            'corporate',
            'downtown',
            'city',
            'central',
            'haihuahotel',
            'china',
        ],
    },
    {
        hotelName: 'Kobe Sannomiya Tokyu REI Hotel',
        semanticTokens: [
            'kobe',
            'sannomiya',
            'tokyu',
            'rei',
            'koby',
            'sanomiya',
            'tokyo',
            'tokyurei',
            'business',
            'central',
            'downtown',
            'japan',
            'kobehotel',
        ],
    },
    {
        hotelName: 'Suites South Burlington',
        semanticTokens: [
            'suites',
            'south',
            'burlington',
            'suit',
            'southern',
            'burlingtn',
            'suits',
            'suth',
            'vermont',
            'vt',
            'extended stay',
            'business',
            'corporate',
            'apartment',
            'southburlington',
        ],
    },
    {
        hotelName:
            'Everbright Convention & Exhibition Centre International Hotel',
        semanticTokens: [
            'everbright',
            'convention',
            'exhibition',
            'international',
            'everbrite',
            'convension',
            'exhibiton',
            'conventioncentre',
            'business',
            'meetings',
            'corporate',
            'conference',
            'shanghai',
            'china',
            'everbrighthotel',
        ],
    },
    {
        hotelName: 'Hilton Garden Inn Pittsburgh University Place',
        semanticTokens: [
            'hilton',
            'garden',
            'inn',
            'pittsburgh',
            'university',
            'hiltn',
            'gardin',
            'pitsburgh',
            'uni',
            'gardens',
            'business',
            'corporate',
            'campus',
            'education',
            'pennsylvania',
            'pa',
            'gardeninn',
        ],
    },
    {
        hotelName: 'Hotel Apogia Nice',
        semanticTokens: [
            'apogia',
            'nice',
            'apogee',
            'nise',
            'apoggia',
            'france',
            'beach',
            'coastal',
            'mediterranean',
            'business',
            'central',
            'apogiahotel',
        ],
    },
    {
        hotelName: 'Paris Las Vegas',
        semanticTokens: [
            'paris',
            'las',
            'vegas',
            'parris',
            'pares',
            'lasvegas',
            'vegus',
            'parislasvegas',
            'caesars',
            'casino',
            'gaming',
            'resort',
            'strip',
            'entertainment',
            'nevada',
            'nv',
            'luxury',
            'shows',
            'eiffel',
            'gambling',
            'nightlife',
            'restaurants',
        ],
    },
    {
        hotelName: 'Catalonia Brussels Hotel',
        semanticTokens: [
            'catalonia',
            'brussels',
            'catalonya',
            'brussles',
            'brussells',
            'catalan',
            'katalonia',
            'belgium',
            'european',
            'business',
            'corporate',
            'central',
            'downtown',
            'cataloniahotel',
            'conference',
            'meetings',
            'eu',
            'european union',
        ],
    },
    {
        hotelName: 'Grand Prince Hotel Shin Takanawa',
        semanticTokens: [
            'grand',
            'prince',
            'shin',
            'takanawa',
            'grnad',
            'princ',
            'shinn',
            'takannawa',
            'tokyo',
            'japan',
            'luxury',
            'grandprince',
            'princehotel',
            'business',
            'corporate',
            'upscale',
            'convention',
            'shinagawa',
            'conference',
        ],
    },
    {
        hotelName: 'Watazen Ryokan Hotel',
        semanticTokens: [
            'watazen',
            'ryokan',
            'watzen',
            'watazenn',
            'ryoken',
            'traditional',
            'kyoto',
            'japan',
            'historic',
            'boutique',
            'cultural',
            'garden',
            'authentic',
            'downtown',
            'central',
            'japanese',
        ],
    },
    {
        hotelName: 'Amba Hotel Charing Cross',
        semanticTokens: [
            'amba',
            'charing',
            'cross',
            'charingcross',
            'charring',
            'ambahotel',
            'london',
            'central',
            'thistle',
            'station',
            'trafalgar',
            'strand',
            'westend',
            'theatreland',
            'business',
            'historic',
            'landmark',
            'victorian',
            'rail',
            'transport',
        ],
    },
    {
        hotelName: 'Imperial Hotel Hong Kong',
        semanticTokens: [
            'imperial',
            'imperal',
            'impirial',
            'hongkong',
            'tsim sha tsui',
            'kowloon',
            'nathan road',
            'business',
            'shopping',
            'central',
            'budget',
            'affordable',
            'downtown',
            'harbour',
            'imperialhotel',
            'city',
        ],
    },
    {
        hotelName: 'Royal Hotel Sanremo',
        semanticTokens: [
            'royal',
            'sanremo',
            'san remo',
            'royel',
            'royle',
            'sanremo',
            'leading hotels',
            'luxury',
            'riviera',
            'italian',
            'italy',
            'mediterranean',
            'beach',
            'casino',
            'historic',
            'elegant',
            'premium',
            'upscale',
            'vacation',
        ],
    },
    {
        hotelName: 'The Park Hotel Visakhapatnam',
        semanticTokens: [
            'park',
            'vizag',
            'visakhapatnam',
            'parks',
            'parke',
            'vizaghotel',
            'beach road',
            'coastal',
            'business',
            'corporate',
            'andhra',
            'luxury',
            'conference',
            'seaside',
            'premium',
            'upscale',
            'parkhotel',
            'meetings',
        ],
    },
    {
        hotelName: 'Staybridge Suites Austin Round Rock',
        semanticTokens: [
            'staybridge',
            'staybrige',
            'roundrock',
            'round rock',
            'austin',
            'suites',
            'extended stay',
            'ihg',
            'intercontinental',
            'texas',
            'tx',
            'corporate',
            'business',
            'apartment',
            'long stay',
            'kitchen',
            'residential',
            'furnished',
        ],
    },
    {
        hotelName: 'Hotel Sunroute Nara',
        semanticTokens: [
            'sunroute',
            'sunrute',
            'sunroot',
            'nara',
            'japan',
            'sotetsu',
            'business',
            'corporate',
            'tourist',
            'temple',
            'cultural',
            'affordable',
            'central',
            'downtown',
            'convention',
            'historic',
            'heritage',
        ],
    },
    {
        hotelName: 'The Tower Hotel',
        semanticTokens: [
            'tower',
            'towr',
            'towers',
            'london',
            'bridge',
            'thistle',
            'guoman',
            'riverside',
            'thames',
            'st katherines',
            'dock',
            'city',
            'business',
            'corporate',
            'landmark',
            'historic',
            'views',
            'towerbridge',
            'central',
        ],
    },
    {
        hotelName: 'The Grand New Delhi Hotel',
        semanticTokens: [
            'grand',
            'grnad',
            'delhi',
            'newdelhi',
            'vasant kunj',
            'luxury',
            'business',
            'corporate',
            'conference',
            'premium',
            'upscale',
            'airport',
            'diplomatic',
            'meetings',
            'convention',
            'grandhotel',
            'executive',
        ],
    },
    {
        hotelName: "Corinthia Hotel St. George's Bay",
        semanticTokens: [
            'corinthia',
            'saint georges',
            'st georges',
            'corintia',
            'malta',
            'mediterranean',
            'bay',
            'beach',
            'luxury',
            'premium',
            'upscale',
            'resort',
            'seaside',
            'waterfront',
            'paceville',
            'saintjulians',
            'stjulians',
            'conference',
        ],
    },
    {
        hotelName: 'Gran Hotel Cervantes by Blue Sea',
        semanticTokens: [
            'gran',
            'cervantes',
            'bluesea',
            'blue sea',
            'grand',
            'cervantes',
            'torremolinos',
            'spain',
            'costa del sol',
            'beach',
            'resort',
            'seaside',
            'vacation',
            'holiday',
            'mediterranean',
            'coastal',
            'family',
        ],
    },
]
